// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UiTestRunner.Data;

#nullable disable

namespace UiTestRunner.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("UiTestRunner.Models.TestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GherkinScript")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("UiTestRunner.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("GherkinScript")
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchRunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScenarioName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("HangfireJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningLog")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RunTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenshotPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
